name: Post Release - Prepare Main for Next Development Cycle

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.1)'
        required: true

env:
  AWS_DEFAULT_REGION: us-east-1

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Extract Major.Minor Version and setup Env variable
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "MAJOR_MINOR=$(echo ${{ github.event.inputs.version }} | sed -E 's/([0-9]+\.[0-9]+)\.[0-9]+/\1/')" >> $GITHUB_ENV

      - name: Get current major.minor version from main branch
        id: get_version
        run: |
          CURRENT_VERSION=$(grep 'public static string version' src/AWS.Distro.OpenTelemetry.AutoInstrumentation/Version.cs | sed -E 's/    public static string version = "([0-9]+\.[0-9]+)\.[0-9]+.*";/\1/')
          echo "CURRENT_MAJOR_MINOR_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Set major and minor for current version
        run: |
          echo "CURRENT_MAJOR=$(echo $CURRENT_MAJOR_MINOR_VERSION | cut -d. -f1)" >> $GITHUB_ENV
          echo "CURRENT_MINOR=$(echo $CURRENT_MAJOR_MINOR_VERSION | cut -d. -f2)" >> $GITHUB_ENV

      - name: Set major and minor for input version
        run: |
          echo "INPUT_MAJOR=$(echo $MAJOR_MINOR | cut -d. -f1)" >> $GITHUB_ENV
          echo "INPUT_MINOR=$(echo $MAJOR_MINOR | cut -d. -f2)" >> $GITHUB_ENV

      - name: Compare major.minor version and skip if behind
        run: |
          if [ "$CURRENT_MAJOR" -gt "$INPUT_MAJOR" ] || { [ "$CURRENT_MAJOR" -eq "$INPUT_MAJOR" ] && [ "$CURRENT_MINOR" -gt "$INPUT_MINOR" ]; }; then
            echo "Input version is behind main's current major.minor version, don't need to update major version"
            exit 1
          fi

  prepare-main:
    runs-on: ubuntu-latest
    needs: check-version
    steps:
      - name: Configure AWS credentials for BOT secrets
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_SECRETS_MANAGER }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Get Bot secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        id: bot_secrets
        with:
          secret-ids: |
            BOT_TOKEN ,${{ secrets.BOT_TOKEN_SECRET_ARN }}
          parse-json-secrets: true

      - name: Setup Git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ env.BOT_TOKEN_GITHUB_RW_PATOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Extract Major.Minor Version and setup Env variable
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "MAJOR_MINOR=$(echo ${{ github.event.inputs.version }} | sed -E 's/([0-9]+\.[0-9]+)\.[0-9]+/\1/')" >> $GITHUB_ENV

      - name: Determine release branch and checkout
        run: |
          RELEASE_BRANCH="release/v${MAJOR_MINOR}.x"
          git fetch origin $RELEASE_BRANCH
          git checkout -b "prepare-main-for-next-dev-cycle-${VERSION}" origin/$RELEASE_BRANCH

      - name: Update version to next development version in main
        # TODO update version in daily_scan.yml
        run: |
          DEV_VERSION="${{ github.event.inputs.version }}.dev0"
          sed -i "s/public static string version = \".*\";/public static string version = \"${DEV_VERSION}\";/" src/AWS.Distro.OpenTelemetry.AutoInstrumentation/Version.cs
          sed -i "s/private readonly string version = \".*\";/private readonly string version = \"${DEV_VERSION}\";/" build/Build.InstallationScripts.cs
          VERSION="${{ github.event.inputs.version }}"
          git add src/AWS.Distro.OpenTelemetry.AutoInstrumentation/Version.cs
          git add build/Build.InstallationScripts.cs

      - name: Append latest release checksum to release-artifacts-metadata.json
        run: |
          ARTIFACT_NAMES=(
            "aws-distro-opentelemetry-dotnet-instrumentation-linux-glibc-arm64.zip"
            "aws-distro-opentelemetry-dotnet-instrumentation-linux-glibc-x64.zip"
            "aws-distro-opentelemetry-dotnet-instrumentation-linux-musl-arm64.zip"
            "aws-distro-opentelemetry-dotnet-instrumentation-linux-musl-x64.zip"
            "aws-distro-opentelemetry-dotnet-instrumentation-windows.zip"
            "aws-otel-dotnet-install.sh"
            "AWS.Otel.DotNet.Auto.psm1"
          )


          BASE_URL="https://github.com/aws-observability/aws-otel-dotnet-instrumentation/releases/download/v${{ github.event.inputs.version }}"
          NEW_RELEASE=$(jq -n --arg version "${{ github.event.inputs.version }}" \
            '{version: $version, checksum: []}')
          for ARTIFACT_NAME in "${ARTIFACT_NAMES[@]}"; do
            curl -L -o "$ARTIFACT_NAME" "${BASE_URL}/${ARTIFACT_NAME}"
            CHECKSUM=$(shasum -a 256 $ARTIFACT_NAME | awk '{ print $1 }')

            NEW_RELEASE=$(echo "$NEW_RELEASE" | jq --arg name "$ARTIFACT_NAME" \
              --arg checksum "$CHECKSUM" \
              '.checksum += [{"name": $name, "checksum": $checksum}]')
          done

          FILE="release-artifacts-metadata.json"
          UPDATED_JSON=$(jq --argjson new_release "$NEW_RELEASE" \
            '.release += [$new_release]' "$FILE")
          echo "$UPDATED_JSON" > "$FILE"

          git add release-artifacts-metadata.json

      - name: Push changes to Github
        run: |
          git commit -m "Prepare main for next development cycle: Update version to ${{ github.event.inputs.version }}"
          git push --set-upstream origin "prepare-main-for-next-dev-cycle-${{ github.event.inputs.version }}"

      - name: Create Pull Request to main
        env:
          GITHUB_TOKEN: ${{ env.BOT_TOKEN_GITHUB_RW_PATOKEN }}
        run: |
          DEV_VERSION="${{ github.event.inputs.version }}.dev0"
          gh pr create --title "Post release $VERSION: Update version to $DEV_VERSION" \
                       --body "This PR prepares the main branch for the next development cycle by updating the version to $DEV_VERSION and updating the image version to be scanned to the latest released.

          This PR should only be merge when release for version v$VERSION is success.

          By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice." \
                       --head prepare-main-for-next-dev-cycle-${VERSION} \
                       --base main